model = "sonnet"
system-prompt = "You are a concise assistant to a software engineer"
reasoning = true
max-tokens = 2048
style = "tokyo-night"

# Anthropic only
anthropic-api-key = ""

# OpenAI only
openai-api-key = ""
reasoning-effort = 4 # GPT-5 only
